INSERT  INTO
	cvc_delivery_info
      ( 
      id                            
      ,number                         
      ,message                        
      ,data                           
      ,state   
      ,create_date                       
      ) 
values
      (
      :cvcDeliveryInfo.id                            
      ,:cvcDeliveryInfo.number                        
      ,:cvcDeliveryInfo.message                       
      ,:cvcDeliveryInfo.data                          
      ,:cvcDeliveryInfo.state 
      ,:cvcDeliveryInfo.createDate                        
      )