INSERT  INTO
	cvc_shipping_batch
      ( 
      id                            
      ,batch_no                       
      ,shipping_count                 
      ,shipping_count_ok              
      ,add_time                       
      ,order_batch_no                 
      ,msg_status                     
      ) 
values
      (
      :cvcShippingBatch.id                            
      ,:cvcShippingBatch.batchNo                       
      ,:cvcShippingBatch.shippingCount                 
      ,:cvcShippingBatch.shippingCountOk               
      ,:cvcShippingBatch.addTime                       
      ,:cvcShippingBatch.orderBatchNo                  
      ,:cvcShippingBatch.msgStatus                     
      )