INSERT  INTO
	cvc_order_info
      ( 
      order_id                      
      ,order_sn                       
      ,user_id   
      ,user_name                      
      ,consignee                      
      ,address                        
      ,tel                            
      ,add_time                       
      ,confirm_time    
      ,batch_no
      ,remark    
      ,get_time           
      ) 
values
      (
      :cvcOrderInfo.id                       
      ,:cvcOrderInfo.orderSn                       
      ,:cvcOrderInfo.userId                      
      ,:cvcOrderInfo.userName                      
      ,:cvcOrderInfo.consignee                     
      ,:cvcOrderInfo.address                       
      ,:cvcOrderInfo.tel                           
      ,:cvcOrderInfo.addTime                       
      ,:cvcOrderInfo.confirmTime                   
      ,:cvcOrderInfo.batchNo 
      ,:cvcOrderInfo.remark
      ,:cvcOrderInfo.getTime                
      )