INSERT  INTO
	cvc_order_info
      ( 
      order_id                      
      ,order_sn                       
      ,user_id                        
      ,user_name                      
      ,order_status                   
      ,tk_order_status                
      ,shipping_status                
      ,pay_status                     
      ,consignee                      
      ,country                        
      ,province                       
      ,city                           
      ,district                       
      ,address                        
      ,zipcode                        
      ,tel                            
      ,mobile                         
      ,email                          
      ,best_time                      
      ,sign_building                  
      ,postscript                     
      ,shipping_id                    
      ,shipping_name                  
      ,pay_id                         
      ,pay_name                       
      ,how_oos                        
      ,how_surplus                    
      ,pack_name                      
      ,card_name                      
      ,card_message                   
      ,inv_payee                      
      ,inv_content                    
      ,goods_amount                   
      ,shipping_fee                   
      ,insure_fee                     
      ,pay_fee                        
      ,pack_fee                       
      ,card_fee                       
      ,money_paid                     
      ,surplus                        
      ,integral                       
      ,integral_money                 
      ,bonus                          
      ,order_amount                   
      ,from_ad                        
      ,referer                        
      ,add_time                       
      ,confirm_time                   
      ,pay_time                       
      ,shipping_time                  
      ,cancel_time                    
      ,refund_time                    
      ,pack_id                        
      ,card_id                        
      ,bonus_id                       
      ,invoice_no                     
      ,extension_code                 
      ,extension_id                   
      ,to_buyer                       
      ,pay_note                       
      ,agency_id                      
      ,inv_type                       
      ,tax                            
      ,is_separate                    
      ,parent_id                      
      ,discount                       
      ,prefer_deliverdate             
      ,enterprise_id                  
      ,custom_date                    
      ,bank                           
      ,enterprise_discount            
      ,gift_card                      
      ,cps_id                         
      ,is_show                        
      ,p_id                           
      ,orderNumber                    
      ,upc_suppliers_id               
      ,ule_order_id                   
      ,bn_order_id                    
      ,back_order_id                  
      ,channel                        
      ,send_type                      
      ,order_type                     
      ,group_no                       
      ,channel_name                   
      ,is_none_channel                
      ,idcard                         
      ) 
values
      (
      :cvcOrderInfo.id                       
      ,:cvcOrderInfo.orderSn                       
      ,:cvcOrderInfo.userId                        
      ,:cvcOrderInfo.userName                      
      ,:cvcOrderInfo.orderStatus                   
      ,:cvcOrderInfo.tkOrderStatus                 
      ,:cvcOrderInfo.shippingStatus                
      ,:cvcOrderInfo.payStatus                     
      ,:cvcOrderInfo.consignee                     
      ,:cvcOrderInfo.country                       
      ,:cvcOrderInfo.province                      
      ,:cvcOrderInfo.city                          
      ,:cvcOrderInfo.district                      
      ,:cvcOrderInfo.address                       
      ,:cvcOrderInfo.zipcode                       
      ,:cvcOrderInfo.tel                           
      ,:cvcOrderInfo.mobile                        
      ,:cvcOrderInfo.email                         
      ,:cvcOrderInfo.bestTime                      
      ,:cvcOrderInfo.signBuilding                  
      ,:cvcOrderInfo.postscript                    
      ,:cvcOrderInfo.shippingId                    
      ,:cvcOrderInfo.shippingName                  
      ,:cvcOrderInfo.payId                         
      ,:cvcOrderInfo.payName                       
      ,:cvcOrderInfo.howOos                        
      ,:cvcOrderInfo.howSurplus                    
      ,:cvcOrderInfo.packName                      
      ,:cvcOrderInfo.cardName                      
      ,:cvcOrderInfo.cardMessage                   
      ,:cvcOrderInfo.invPayee                      
      ,:cvcOrderInfo.invContent                    
      ,:cvcOrderInfo.goodsAmount                   
      ,:cvcOrderInfo.shippingFee                   
      ,:cvcOrderInfo.insureFee                     
      ,:cvcOrderInfo.payFee                        
      ,:cvcOrderInfo.packFee                       
      ,:cvcOrderInfo.cardFee                       
      ,:cvcOrderInfo.moneyPaid                     
      ,:cvcOrderInfo.surplus                       
      ,:cvcOrderInfo.integral                      
      ,:cvcOrderInfo.integralMoney                 
      ,:cvcOrderInfo.bonus                         
      ,:cvcOrderInfo.orderAmount                   
      ,:cvcOrderInfo.fromAd                        
      ,:cvcOrderInfo.referer                       
      ,:cvcOrderInfo.addTime                       
      ,:cvcOrderInfo.confirmTime                   
      ,:cvcOrderInfo.payTime                       
      ,:cvcOrderInfo.shippingTime                  
      ,:cvcOrderInfo.cancelTime                    
      ,:cvcOrderInfo.refundTime                    
      ,:cvcOrderInfo.packId                        
      ,:cvcOrderInfo.cardId                        
      ,:cvcOrderInfo.bonusId                       
      ,:cvcOrderInfo.invoiceNo                     
      ,:cvcOrderInfo.extensionCode                 
      ,:cvcOrderInfo.extensionId                   
      ,:cvcOrderInfo.toBuyer                       
      ,:cvcOrderInfo.payNote                       
      ,:cvcOrderInfo.agencyId                      
      ,:cvcOrderInfo.invType                       
      ,:cvcOrderInfo.tax                           
      ,:cvcOrderInfo.isSeparate                    
      ,:cvcOrderInfo.parentId                      
      ,:cvcOrderInfo.discount                      
      ,:cvcOrderInfo.preferDeliverdate             
      ,:cvcOrderInfo.enterpriseId                  
      ,:cvcOrderInfo.customDate                    
      ,:cvcOrderInfo.bank                          
      ,:cvcOrderInfo.enterpriseDiscount            
      ,:cvcOrderInfo.giftCard                      
      ,:cvcOrderInfo.cpsId                         
      ,:cvcOrderInfo.isShow                        
      ,:cvcOrderInfo.pId                           
      ,:cvcOrderInfo.ordernumber                   
      ,:cvcOrderInfo.upcSuppliersId                
      ,:cvcOrderInfo.uleOrderId                    
      ,:cvcOrderInfo.bnOrderId                     
      ,:cvcOrderInfo.backOrderId                   
      ,:cvcOrderInfo.channel                       
      ,:cvcOrderInfo.sendType                      
      ,:cvcOrderInfo.orderType                     
      ,:cvcOrderInfo.groupNo                       
      ,:cvcOrderInfo.channelName                   
      ,:cvcOrderInfo.isNoneChannel                 
      ,:cvcOrderInfo.idcard                        
      )