INSERT  INTO
	cvc_delivery_goods
      ( 
      delivery_id                    
      ,goods_id                       
      ,product_id                     
      ,product_sn                     
      ,goods_name                     
      ,brand_name                     
      ,goods_sn                       
      ,extension_code                 
      ,send_number                    
      ,goods_attr                     
      ,system_sku                     
      ,goods_price                    
      ) 
values
      (
      :cvcDeliveryGoods.deliveryId                    
      ,:cvcDeliveryGoods.goodsId                       
      ,:cvcDeliveryGoods.productId                     
      ,:cvcDeliveryGoods.productSn                     
      ,:cvcDeliveryGoods.goodsName                     
      ,:cvcDeliveryGoods.brandName                     
      ,:cvcDeliveryGoods.goodsSn                       
      ,:cvcDeliveryGoods.extensionCode                 
      ,:cvcDeliveryGoods.sendNumber                    
      ,:cvcDeliveryGoods.goodsAttr                     
      ,:cvcDeliveryGoods.systemSku                     
      ,:cvcDeliveryGoods.goodsPrice                    
      )