INSERT  INTO
	cvc_checking_account_order
      ( 
      id                            
      ,checking_account_id            
      ,order_id                       
      ,shipping_name                  
      ,is_add_checking_account        
      ,add_checking_account_time      
      ,invoice_no                     
      ,goods_sn                       
      ,goods_number                   
      ,address                        
      ,consignee                      
      ,mobile                         
      ,signin_date                    
      ) 
values
      (
      :cvcCheckingAccountOrder.id                            
      ,:cvcCheckingAccountOrder.checkingAccountId             
      ,:cvcCheckingAccountOrder.orderId                       
      ,:cvcCheckingAccountOrder.shippingName                  
      ,:cvcCheckingAccountOrder.isAddCheckingAccount          
      ,:cvcCheckingAccountOrder.addCheckingAccountTime        
      ,:cvcCheckingAccountOrder.invoiceNo                     
      ,:cvcCheckingAccountOrder.goodsSn                       
      ,:cvcCheckingAccountOrder.goodsNumber                   
      ,:cvcCheckingAccountOrder.address                       
      ,:cvcCheckingAccountOrder.consignee                     
      ,:cvcCheckingAccountOrder.mobile                        
      ,:cvcCheckingAccountOrder.signinDate                    
      )