INSERT  INTO
	cvc_delivery_order
      ( 
      delivery_id                   
      ,delivery_sn                    
      ,order_sn                       
      ,order_id                       
      ,invoice_no                     
      ,add_time                       
      ,shipping_id                    
      ,shipping_name                  
      ,user_id                        
      ,action_user                    
      ,consignee                      
      ,address                        
      ,country                        
      ,province                       
      ,city                           
      ,district                       
      ,sign_building                  
      ,email                          
      ,zipcode                        
      ,tel                            
      ,mobile                         
      ,best_time                      
      ,postscript                     
      ,how_oos                        
      ,insure_fee                     
      ,shipping_fee                   
      ,update_time                    
      ,suppliers_id                   
      ,status                         
      ,tk_status                      
      ,agency_id                      
      ,pre_arrival_date               
      ,signin_date                    
      ) 
values
      (
      :cvcDeliveryOrder.deliveryId                    
      ,:cvcDeliveryOrder.deliverySn                    
      ,:cvcDeliveryOrder.orderSn                       
      ,:cvcDeliveryOrder.orderId                       
      ,:cvcDeliveryOrder.invoiceNo                     
      ,:cvcDeliveryOrder.addTime                       
      ,:cvcDeliveryOrder.shippingId                    
      ,:cvcDeliveryOrder.shippingName                  
      ,:cvcDeliveryOrder.userId                        
      ,:cvcDeliveryOrder.actionUser                    
      ,:cvcDeliveryOrder.consignee                     
      ,:cvcDeliveryOrder.address                       
      ,:cvcDeliveryOrder.country                       
      ,:cvcDeliveryOrder.province                      
      ,:cvcDeliveryOrder.city                          
      ,:cvcDeliveryOrder.district                      
      ,:cvcDeliveryOrder.signBuilding                  
      ,:cvcDeliveryOrder.email                         
      ,:cvcDeliveryOrder.zipcode                       
      ,:cvcDeliveryOrder.tel                           
      ,:cvcDeliveryOrder.mobile                        
      ,:cvcDeliveryOrder.bestTime                      
      ,:cvcDeliveryOrder.postscript                    
      ,:cvcDeliveryOrder.howOos                        
      ,:cvcDeliveryOrder.insureFee                     
      ,:cvcDeliveryOrder.shippingFee                   
      ,:cvcDeliveryOrder.updateTime                    
      ,:cvcDeliveryOrder.suppliersId                   
      ,:cvcDeliveryOrder.status                        
      ,:cvcDeliveryOrder.tkStatus                      
      ,:cvcDeliveryOrder.agencyId                      
      ,:cvcDeliveryOrder.preArrivalDate                
      ,:cvcDeliveryOrder.signinDate                    
      )