INSERT  INTO
	cvc_shipping
      ( 
      shipping_id                   
      ,shipping_code                  
      ,shipping_name                  
      ,shipping_desc                  
      ,insure                         
      ,support_cod                    
      ,enabled                        
      ,shipping_print                 
      ,print_bg                       
      ,config_lable                   
      ,print_model                    
      ,shipping_order                 
      ,suppliers_id                   
      ,is_default                     
      ) 
values
      (
      :cvcShipping.shippingId                    
      ,:cvcShipping.shippingCode                  
      ,:cvcShipping.shippingName                  
      ,:cvcShipping.shippingDesc                  
      ,:cvcShipping.insure                        
      ,:cvcShipping.supportCod                    
      ,:cvcShipping.enabled                       
      ,:cvcShipping.shippingPrint                 
      ,:cvcShipping.printBg                       
      ,:cvcShipping.configLable                   
      ,:cvcShipping.printModel                    
      ,:cvcShipping.shippingOrder                 
      ,:cvcShipping.suppliersId                   
      ,:cvcShipping.isDefault                     
      )